### ISSUE TITLE
ksmbd should detect if IPv6 support is enabled

### ISSUE THREAD

**Issue by julius59** [namjaejeon/ksmbd#406]
Hi,

ksmbd reports the following error on my system: `ksmbd: Can't create socket for ipv6, try ipv4: -97`

This is expected though, because I have a custom kernel with IPv6 disabled (_# CONFIG_IPV6 is not set_ or "ipv6.disable=1").
It would be nice if this could be detected and not logged as an error.

Otherwise it's working quite well, well done! :)

**Comment by namjaejeon** [comment]
@julius59 Thanks for your report! I will downgrade this message to the debug.

**Comment by namjaejeon** [comment]
FIXED(https://github.com/namjaejeon/ksmbd/commit/2aca7cf5c8ee3c484bc36ecb4c178ea09c46317a), Can you confirm your issue is fixed ?

**Comment by julius59** [comment]
Yes the error message is gone, thanks!

I'm not sure if this could be handled differently though? The call to `sock_create(PF_INET6...)` is still happening.
I guess probing if the kernel supports IPv6 would be better, if this is somehow feasible?

Anyway, this is already good enough as far as I'm concerned.
